"""initial schema

Revision ID: 908138e3c1b2
Revises: 
Create Date: 2026-05-22 14:41:08.718343

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '908138e3c1b2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Habilitar extensions necesarias en PostgreSQL. La imagen pgvector/pgvector
    # ya las trae; este CREATE EXTENSION IF NOT EXISTS las marca como
    # dependencias explícitas del schema (Alembic las recreará en una DB nueva).
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "btree_gin"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "vector"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_oid', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_oid'), 'audit_log', ['actor_oid'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_table('categories',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('docs', sa.Integer(), nullable=False),
    sa.Column('vigentes', sa.Integer(), nullable=False),
    sa.Column('autoritativos', sa.Integer(), nullable=False),
    sa.Column('score_avg', sa.Float(), nullable=False),
    sa.Column('obsolescencia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('doc_types',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('hot_topics_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('queries_30d', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('is_gap', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recent_activity',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('actor_oid', sa.String(length=128), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('ref_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recent_activity_actor_oid'), 'recent_activity', ['actor_oid'], unique=False)
    op.create_index(op.f('ix_recent_activity_at'), 'recent_activity', ['at'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by_oid', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('oid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=16), nullable=False),
    sa.Column('carpetas_owned', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('puede_gobernar_taxonomia', sa.Boolean(), nullable=False),
    sa.Column('puede_aprobar_taxonomia', sa.Boolean(), nullable=False),
    sa.Column('puede_ver_metricas_globales', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('carpeta', sa.String(length=8), nullable=False),
    sa.Column('tipo', sa.String(length=8), nullable=False),
    sa.Column('autoritativo', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('autor_oid', sa.String(length=128), nullable=True),
    sa.Column('autor_name', sa.String(length=255), nullable=False),
    sa.Column('autor_role', sa.String(length=64), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('citas', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('anonimizado', sa.Boolean(), nullable=False),
    sa.Column('fragmentos', sa.Integer(), nullable=False),
    sa.Column('paginas', sa.Integer(), nullable=False),
    sa.Column('formato', sa.String(length=16), nullable=False),
    sa.Column('aprobador_name', sa.String(length=255), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blob_path', sa.String(length=1024), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_oid'], ['users.oid'], ),
    sa.ForeignKeyConstraint(['carpeta'], ['categories.code'], ),
    sa.ForeignKeyConstraint(['tipo'], ['doc_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_autor_oid'), 'documents', ['autor_oid'], unique=False)
    op.create_index(op.f('ix_documents_carpeta'), 'documents', ['carpeta'], unique=False)
    op.create_index(op.f('ix_documents_estado'), 'documents', ['estado'], unique=False)
    op.create_index('ix_documents_fecha_desc', 'documents', [sa.literal_column('fecha DESC')], unique=False)
    op.create_index('ix_documents_score_desc', 'documents', [sa.literal_column('score DESC')], unique=False)
    op.create_index(op.f('ix_documents_tipo'), 'documents', ['tipo'], unique=False)
    op.create_table('ingestion_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('paginas', sa.Integer(), nullable=False),
    sa.Column('carpeta_sugerida', sa.String(length=8), nullable=True),
    sa.Column('tipo_sugerido', sa.String(length=8), nullable=True),
    sa.Column('aprobador_oid', sa.String(length=128), nullable=True),
    sa.Column('aprobador_name', sa.String(length=255), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fuente_original', sa.String(length=1024), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by_oid', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('blob_path', sa.String(length=1024), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_oid'], ['users.oid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_items_status'), 'ingestion_items', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_oid', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_stage', sa.String(length=4), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('agent_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='LangGraph state checkpointer — Fase 2'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_oid'], ['users.oid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_owner_oid'), 'sessions', ['owner_oid'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('capture_scores',
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('specificity', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('reusability', sa.Float(), nullable=False),
    sa.Column('uniqueness', sa.Float(), nullable=False),
    sa.Column('value_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_doc_idx')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('error_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_messages_started_at'), 'messages', ['started_at'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_oid', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_result', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_oid'], ['users.oid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_asked_at'), 'queries', ['asked_at'], unique=False)
    op.create_index(op.f('ix_queries_user_oid'), 'queries', ['user_oid'], unique=False)
    op.create_table('query_citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_citations_document_id'), 'query_citations', ['document_id'], unique=False)
    op.create_index(op.f('ix_query_citations_query_id'), 'query_citations', ['query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_citations_query_id'), table_name='query_citations')
    op.drop_index(op.f('ix_query_citations_document_id'), table_name='query_citations')
    op.drop_table('query_citations')
    op.drop_index(op.f('ix_queries_user_oid'), table_name='queries')
    op.drop_index(op.f('ix_queries_asked_at'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_messages_started_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('capture_scores')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_owner_oid'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_ingestion_items_status'), table_name='ingestion_items')
    op.drop_table('ingestion_items')
    op.drop_index(op.f('ix_documents_tipo'), table_name='documents')
    op.drop_index('ix_documents_score_desc', table_name='documents')
    op.drop_index('ix_documents_fecha_desc', table_name='documents')
    op.drop_index(op.f('ix_documents_estado'), table_name='documents')
    op.drop_index(op.f('ix_documents_carpeta'), table_name='documents')
    op.drop_index(op.f('ix_documents_autor_oid'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_index(op.f('ix_recent_activity_at'), table_name='recent_activity')
    op.drop_index(op.f('ix_recent_activity_actor_oid'), table_name='recent_activity')
    op.drop_table('recent_activity')
    op.drop_table('hot_topics_snapshot')
    op.drop_table('doc_types')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_oid'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
